version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/app/data  # Bind mount to persist data
    restart: always  # Optional, restarts the container on failure
