version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - DATA_PATH=/app/app/data
    restart: always 
